In [ ]:
#problem 1

import pandas as pd
df = pd.read_csv('employees_large.csv')
avg_salary = df.groupby('department')['salary'].mean()

highest_salary_dept = avg_salary.idxmax()

print("Average salary per department:\n", avg_salary)
print("\nDepartment with the highest average salary:", highest_salary_dept)

       Name  Age  Salary   Department
0     Alice   25   45000           IT
1       Bob   30   70000           HR
2   Charlie   22   30000    Marketing
3     David   35   80000      Finance
4       Eva   28   50000           IT
5     Frank   40  120000  Engineering
6     Grace   32   62000           HR
7    Hannah   27   48000    Marketing
8       Ian   29   75000      Finance
9      Jack   26   46000           IT
10    Karen   31   71000           HR
11      Leo   38   85000      Finance
12     Mona   23   32000    Marketing
13     Nina   34   69000           HR
14    Oscar   45  130000  Engineering
15     Paul   41  110000  Engineering
16    Quinn   37   72000      Finance
17   Rachel   33   65000    Marketing
18    Steve   39   90000           IT
19      Tom   50  140000  Engineering

In [ ]:
#problem 2
import pandas as pd

df = pd.read_csv('sales_large.csv')

total_sales = df.groupby(['region', 'product'])['sales'].sum()

highest_sales_product = df.groupby('product')['sales'].sum().idxmax()

print("Total sales per product in each region:\n", total_sales)
print("\nProduct with the highest total sales:", highest_sales_product)

     Region  Product  Sales
0      East   Apples   5000
1      West  Bananas   7000
2      East  Oranges   4000
3      West   Apples   6000
4     South  Oranges   3000
5     North  Bananas   9000
6      East  Bananas   8500
7      West  Oranges   7500
8     South   Apples   6700
9     North   Apples   7200
10    South  Bananas   5100
11  Central  Oranges   8000
12     East  Oranges   4800
13     West   Apples   5600
14    North  Oranges   4900
15    South   Apples   6200
16     West  Bananas   7700
17  Central   Apples   9000
18     East  Oranges   5100
19     West   Apples   7300

In [ ]:
#question 4
import numpy as np

data = np.random.rand(10000)  # 'rand' generates numbers between 0 and 1

mean = np.mean(data)

median = np.median(data)

# Compute the standard deviation
std_dev = np.std(data)import numpy as np

# Generate a NumPy array with 10,000 random real numbers
data = np.random.rand(10000)

# Compute the minimum and maximum values
minimum = np.min(data)
maximum = np.max(data)

# Perform min-max scaling
scaled_data = (data - minimum) / (maximum - minimum)

# Print some examples of the original and scaled data
print("Original Data (first 5 values):", data[:5])
print("Scaled Data (first 5 values):", scaled_data[:5])

# Verify the range of the scaled data
print("Scaled Data Minimum:", np.min(scaled_data))
print("Scaled Data Maximum:", np.max(scaled_data))


minimum = np.min(data)


maximum = np.max(data)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Minimum:", minimum)
print("Maximum:", maximum)

Mean: 0.5002484718151237
Median: 0.4983412142972913
Standard Deviation: 0.28703897319538874
Minimum: 0.00019342352201390245
Maximum: 0.9998776529542418

In [ ]:
#problem 5
temperatures = [28, 32, 35, 31, 33, 27, 25, 34, 30, 29, 28, 27, 35, 32, 30, 31, 31, 33, 32, 36, 34, 29, 28, 27, 35, 32, 30, 31, 31]
above_32 = [temp for temp in temperatures if temp > 32]
print(above_32)

classified_temps = [(temp, "Hot" if temp > 35 else "Warm" if temp > 30 else "Cool") for temp in temperatures]
print(classified_temps)

avg_temp = sum(temperatures) / len(temperatures)
temp_differences = [temp - avg_temp for temp in temperatures]
print(temp_differences)

[35, 33, 34, 35, 33, 36, 34, 35]
[(28, 'Cool'), (32, 'Warm'), (35, 'Warm'), (31, 'Warm'), (33, 'Warm'), (27, 'Cool'), (25, 'Cool'), (34, 'Warm'), (30, 'Cool'), (29, 'Cool'), (28, 'Cool'), (27, 'Cool'), (35, 'Warm'), (32, 'Warm'), (30, 'Cool'), (31, 'Warm'), (31, 'Warm'), (33, 'Warm'), (32, 'Warm'), (36, 'Hot'), (34, 'Warm'), (29, 'Cool'), (28, 'Cool'), (27, 'Cool'), (35, 'Warm'), (32, 'Warm'), (30, 'Cool'), (31, 'Warm'), (31, 'Warm')]
[-2.8965517241379324, 1.1034482758620676, 4.103448275862068, 0.10344827586206762, 2.1034482758620676, -3.8965517241379324, -5.896551724137932, 3.1034482758620676, -0.8965517241379324, -1.8965517241379324, -2.8965517241379324, -3.8965517241379324, 4.103448275862068, 1.1034482758620676, -0.8965517241379324, 0.10344827586206762, 0.10344827586206762, 2.1034482758620676, 1.1034482758620676, 5.103448275862068, 3.1034482758620676, -1.8965517241379324, -2.8965517241379324, -3.8965517241379324, 4.103448275862068, 1.1034482758620676, -0.8965517241379324, 0.10344827586206762, 0.10344827586206762]